'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { BadgeCheck, FilePlus2, Handshake, ShieldCheck, UsersRound } from 'lucide-react'

export type BrandProfile = { id: string; brand_name: string; description: string; website_url: string }
export type Opportunity = { id: string; title: string; description: string; sport: string; province: string; age_note: string; benefit_note: string; deadline_at: string | null; status: string; created_at: string }
export type Interest = { id: string; opportunity_id: string; message: string; status: string; created_at: string; athlete_profiles: { display_name: string; province: string | null; position: string | null; verification_level: string } | null }

const field = { width: '100%', boxSizing: 'border-box' as const, border: '1px solid #d9dee5', borderRadius: 9, minHeight: 42, padding: '9px 11px', font: '600 13px var(--font-sarabun)', background: '#fff' }
const label = { display: 'block', marginBottom: 6, color: '#536171', font: '800 10px var(--font-oswald)', letterSpacing: 1 }

export default function SponsorClient({ profile, opportunities, interests }: { profile: BrandProfile | null; opportunities: Opportunity[]; interests: Interest[] }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('')
  const [brand, setBrand] = useState({ brandName: profile?.brand_name ?? '', description: profile?.description ?? '', websiteUrl: profile?.website_url ?? '' })
  const [opportunity, setOpportunity] = useState({ title: '', description: '', sport: 'football', province: '', ageNote: '', benefitNote: '', deadlineAt: '' })
  const submit = async (path: string, body: object, success: string) => { setBusy(true); setMessage(''); const response = await fetch(path, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json().catch(() => null) as { error?: string } | null; setBusy(false); setMessage(response.ok ? success : data?.error ?? 'ดำเนินการไม่สำเร็จ'); if (response.ok) router.refresh() }
  const grouped = new Map(opportunities.map(item => [item.id, interests.filter(entry => entry.opportunity_id === item.id)]))
  return <div style={{ display: 'grid', gap: 16 }}>
    {message && <p role="status" style={{ margin: 0, borderRadius: 10, padding: '11px 13px', background: message.includes('ไม่สำเร็จ') ? '#fff1f1' : '#ecfdf5', color: message.includes('ไม่สำเร็จ') ? '#b42318' : '#166534', fontSize: 13, fontWeight: 700 }}>{message}</p>}
    <section style={{ display: 'grid', gap: 12, gridTemplateColumns: 'repeat(auto-fit,minmax(190px,1fr))' }}><div style={{ background: '#101827', color: 'white', borderRadius: 14, padding: 16 }}><Handshake size={19} color="#f5c518" /><b style={{ display: 'block', font: '800 30px var(--font-oswald)', marginTop: 7 }}>{opportunities.length}</b><span style={{ color: 'rgba(255,255,255,.7)', fontSize: 12 }}>โอกาสที่สร้างแล้ว</span></div><div style={{ background: '#fff', border: '1px solid #e3e6ea', borderRadius: 14, padding: 16 }}><UsersRound size={19} color="#CC0001" /><b style={{ display: 'block', font: '800 30px var(--font-oswald)', marginTop: 7 }}>{interests.length}</b><span style={{ color: '#667085', fontSize: 12 }}>นักกีฬาสนใจด้วยตนเอง</span></div><div style={{ background: '#fff9e8', border: '1px solid #f2df9e', borderRadius: 14, padding: 16 }}><ShieldCheck size={19} color="#a16207" /><p style={{ color: '#79570e', fontSize: 12, lineHeight: 1.45, margin: '8px 0 0' }}>ไม่มีข้อมูลติดต่อเด็กในระบบนี้</p></div></section>
    <section style={{ background: '#fff', border: '1px solid #e3e6ea', borderTop: '4px solid #CC0001', borderRadius: 14, padding: 18 }}><div style={{ display: 'flex', gap: 9, alignItems: 'center', marginBottom: 14 }}><BadgeCheck size={20} color="#CC0001" /><div><p style={{ ...label, color: '#CC0001', margin: 0 }}>BRAND IDENTITY</p><h2 style={{ margin: '2px 0 0', fontSize: 21 }}>{profile ? 'ข้อมูลแบรนด์' : 'สร้าง Brand Profile'}</h2></div></div><div style={{ display: 'grid', gap: 10, gridTemplateColumns: 'repeat(auto-fit,minmax(210px,1fr))' }}><label><span style={label}>ชื่อแบรนด์ / องค์กร</span><input required value={brand.brandName} onChange={e => setBrand({ ...brand, brandName: e.target.value })} style={field} placeholder="เช่น BALLSAI Foundation" /></label><label><span style={label}>เว็บไซต์ (ไม่บังคับ)</span><input value={brand.websiteUrl} onChange={e => setBrand({ ...brand, websiteUrl: e.target.value })} style={field} placeholder="https://..." /></label></div><label style={{ display: 'block', marginTop: 10 }}><span style={label}>คุณทำอะไร และอยากสนับสนุนแบบไหน</span><textarea value={brand.description} onChange={e => setBrand({ ...brand, description: e.target.value })} style={{ ...field, minHeight: 76, resize: 'vertical' }} maxLength={1200} placeholder="อธิบายตัวตนและเจตนาของแบรนด์อย่างชัดเจน" /></label><button disabled={busy} onClick={() => void submit('/api/sponsor/profile', brand, 'บันทึก Brand Profile แล้ว')} style={{ marginTop: 12, border: 0, borderRadius: 9, padding: '11px 14px', background: '#172033', color: 'white', fontWeight: 900 }}>{busy ? 'กำลังบันทึก...' : 'บันทึก Brand Profile'}</button></section>
    {profile && <section style={{ display: 'grid', gap: 16, gridTemplateColumns: 'minmax(0,.85fr) minmax(0,1.15fr)' }}><form onSubmit={event => { event.preventDefault(); void submit('/api/sponsor/opportunities', opportunity, 'เปิดโอกาสสนับสนุนแล้ว') }} style={{ background: '#101827', color: 'white', borderRadius: 14, padding: 18 }}><div style={{ display: 'flex', gap: 8, alignItems: 'center', marginBottom: 13 }}><FilePlus2 size={20} color="#f5c518" /><div><p style={{ ...label, color: '#f5c518', margin: 0 }}>NEW OPPORTUNITY</p><h2 style={{ margin: '2px 0 0', fontSize: 21 }}>เปิดโอกาสสนับสนุน</h2></div></div><div style={{ display: 'grid', gap: 9 }}><label><span style={{ ...label, color: 'rgba(255,255,255,.75)' }}>หัวข้อ</span><input required value={opportunity.title} onChange={e => setOpportunity({ ...opportunity, title: e.target.value })} style={field} placeholder="เช่น ทุนอุปกรณ์สำหรับนักฟุตบอลเยาวชน" /></label><label><span style={{ ...label, color: 'rgba(255,255,255,.75)' }}>รายละเอียด</span><textarea required minLength={20} value={opportunity.description} onChange={e => setOpportunity({ ...opportunity, description: e.target.value })} style={{ ...field, minHeight: 82, resize: 'vertical' }} placeholder="เกณฑ์และเจตนาของโอกาสนี้" /></label><div style={{ display: 'grid', gap: 8, gridTemplateColumns: '1fr 1fr' }}><label><span style={{ ...label, color: 'rgba(255,255,255,.75)' }}>กีฬา</span><select value={opportunity.sport} onChange={e => setOpportunity({ ...opportunity, sport: e.target.value })} style={field}><option value="football">ฟุตบอล</option><option value="futsal">ฟุตซอล</option></select></label><label><span style={{ ...label, color: 'rgba(255,255,255,.75)' }}>จังหวัด (ไม่บังคับ)</span><input value={opportunity.province} onChange={e => setOpportunity({ ...opportunity, province: e.target.value })} style={field} /></label></div><label><span style={{ ...label, color: 'rgba(255,255,255,.75)' }}>ช่วงอายุ / หมายเหตุ</span><input value={opportunity.ageNote} onChange={e => setOpportunity({ ...opportunity, ageNote: e.target.value })} style={field} placeholder="เช่น อายุ 12–16 ปี" /></label><label><span style={{ ...label, color: 'rgba(255,255,255,.75)' }}>สิ่งที่สนับสนุน</span><input value={opportunity.benefitNote} onChange={e => setOpportunity({ ...opportunity, benefitNote: e.target.value })} style={field} placeholder="เช่น อุปกรณ์, ทุนเดินทาง" /></label><label><span style={{ ...label, color: 'rgba(255,255,255,.75)' }}>ปิดรับ (ไม่บังคับ)</span><input type="datetime-local" value={opportunity.deadlineAt} onChange={e => setOpportunity({ ...opportunity, deadlineAt: e.target.value })} style={field} /></label></div><button disabled={busy} style={{ width: '100%', marginTop: 13, border: 0, borderRadius: 9, padding: 12, background: '#f5c518', color: '#101827', fontWeight: 900 }}>{busy ? 'กำลังเปิด...' : 'เผยแพร่โอกาส'}</button></form>
      <section style={{ background: '#fff', border: '1px solid #e3e6ea', borderRadius: 14, padding: 18 }}><p style={{ ...label, color: '#CC0001', margin: 0 }}>ATHLETE-INITIATED INTEREST</p><h2 style={{ margin: '3px 0 13px', fontSize: 21 }}>ผู้ที่แสดงความสนใจ</h2>{opportunities.length === 0 ? <p style={{ color: '#788290', fontSize: 13 }}>เปิดโอกาสแรกเพื่อให้ผู้ที่มีโปรไฟล์สาธารณะเลือกสมัครด้วยตัวเอง</p> : <div style={{ display: 'grid', gap: 11 }}>{opportunities.map(item => <article key={item.id} style={{ border: '1px solid #e4e7eb', borderRadius: 11, padding: 12 }}><b>{item.title}</b><p style={{ margin: '4px 0 8px', color: '#788290', fontSize: 12 }}>{grouped.get(item.id)?.length ?? 0} คนสนใจ</p>{(grouped.get(item.id) ?? []).map(interest => <div key={interest.id} style={{ borderTop: '1px solid #edf0f2', paddingTop: 8, marginTop: 8 }}><b style={{ fontSize: 13 }}>{interest.athlete_profiles?.display_name ?? 'นักกีฬา'}</b><span style={{ color: '#687586', fontSize: 12 }}> · {interest.athlete_profiles?.position ?? 'ไม่ระบุตำแหน่ง'} · {interest.athlete_profiles?.province ?? 'ไม่ระบุจังหวัด'}</span>{interest.message && <p style={{ color: '#4b5563', fontSize: 12, lineHeight: 1.45, margin: '5px 0 0' }}>“{interest.message}”</p>}</div>)}</article>)}</div>}<p style={{ borderTop: '1px solid #edf0f2', marginTop: 13, paddingTop: 11, color: '#687586', fontSize: 11, lineHeight: 1.5 }}>ข้อมูลนี้ไม่ใช่การคัดเลือกหรือสัญญา และไม่รวมข้อมูลติดต่อของนักกีฬา</p></section>
    </section>}
  </div>
}
