export const samplePlayerRanks = [
  {
    id: 'sample-player-1',
    player_id: null,
    player_name: 'ธีรภัทร ใจกล้า',
    team: 'Ayutthaya Falcons',
    province: 'พระนครศรีอยุธยา',
    position: 'FW',
    ovr: 82,
    pts: 2140,
    pac: 86,
    sho: 84,
    pas: 72,
    dri: 81,
    def: 48,
    rank_change: 25,
    sport: 'football',
    season: '2026',
  },
  {
    id: 'sample-player-2',
    player_id: null,
    player_name: 'ณัฐวุฒิ ศรีสนาม',
    team: 'Bangkok Youth FC',
    province: 'กรุงเทพฯ',
    position: 'MF',
    ovr: 80,
    pts: 2035,
    pac: 78,
    sho: 74,
    pas: 87,
    dri: 84,
    def: 65,
    rank_change: 18,
    sport: 'football',
    season: '2026',
  },
  {
    id: 'sample-player-3',
    player_id: null,
    player_name: 'พีรวิชญ์ คำเมือง',
    team: 'Chiang Mai City',
    province: 'เชียงใหม่',
    position: 'GK',
    ovr: 79,
    pts: 1988,
    pac: 62,
    sho: 35,
    pas: 70,
    dri: 58,
    def: 88,
    rank_change: 12,
    sport: 'football',
    season: '2026',
  },
  {
    id: 'sample-player-4',
    player_id: null,
    player_name: 'ภาคิน รัตนชัย',
    team: 'Chonburi Academy',
    province: 'ชลบุรี',
    position: 'DF',
    ovr: 77,
    pts: 1875,
    pac: 74,
    sho: 45,
    pas: 68,
    dri: 62,
    def: 86,
    rank_change: 8,
    sport: 'football',
    season: '2026',
  },
  {
    id: 'sample-player-5',
    player_id: null,
    player_name: 'กิตติพงษ์ แก้วใส',
    team: 'Korat United',
    province: 'นครราชสีมา',
    position: 'FW',
    ovr: 75,
    pts: 1742,
    pac: 82,
    sho: 78,
    pas: 61,
    dri: 76,
    def: 42,
    rank_change: -4,
    sport: 'football',
    season: '2026',
  },
  {
    id: 'sample-player-6',
    player_id: null,
    player_name: 'ศิวกร เพชรดำ',
    team: 'Hat Yai Juniors',
    province: 'สงขลา',
    position: 'MF',
    ovr: 74,
    pts: 1685,
    pac: 75,
    sho: 68,
    pas: 79,
    dri: 77,
    def: 60,
    rank_change: 5,
    sport: 'football',
    season: '2026',
  },
  {
    id: 'sample-player-7',
    player_id: null,
    player_name: 'ชยพล วงศ์สว่าง',
    team: 'Rayong Wave',
    province: 'ระยอง',
    position: 'DF',
    ovr: 72,
    pts: 1590,
    pac: 70,
    sho: 40,
    pas: 63,
    dri: 60,
    def: 81,
    rank_change: 0,
    sport: 'football',
    season: '2026',
  },
  {
    id: 'sample-player-8',
    player_id: null,
    player_name: 'อัครเดช นิลทอง',
    team: 'Ubon Rising',
    province: 'อุบลราชธานี',
    position: 'FW',
    ovr: 71,
    pts: 1515,
    pac: 79,
    sho: 73,
    pas: 58,
    dri: 72,
    def: 39,
    rank_change: 14,
    sport: 'football',
    season: '2026',
  },
  {
    id: 'sample-player-9',
    player_id: null,
    player_name: 'ธนกฤต สายชล',
    team: 'Phuket Sea FC',
    province: 'ภูเก็ต',
    position: 'GK',
    ovr: 70,
    pts: 1460,
    pac: 59,
    sho: 30,
    pas: 64,
    dri: 55,
    def: 80,
    rank_change: -2,
    sport: 'football',
    season: '2026',
  },
  {
    id: 'sample-player-10',
    player_id: null,
    player_name: 'รชต เหลืองอร่าม',
    team: 'Nonthaburi Foxes',
    province: 'นนทบุรี',
    position: 'MF',
    ovr: 69,
    pts: 1398,
    pac: 71,
    sho: 64,
    pas: 73,
    dri: 70,
    def: 58,
    rank_change: 3,
    sport: 'football',
    season: '2026',
  },
  {
    id: 'sample-player-11',
    player_id: null,
    player_name: 'ชินวัตร ทองดี',
    team: 'Saraburi Bulls',
    province: 'สระบุรี',
    position: 'DF',
    ovr: 68,
    pts: 1320,
    pac: 67,
    sho: 38,
    pas: 61,
    dri: 58,
    def: 77,
    rank_change: 1,
    sport: 'football',
    season: '2026',
  },
  {
    id: 'sample-player-12',
    player_id: null,
    player_name: 'เมธาสิทธิ์ มีชัย',
    team: 'Nakhon Pathom Stars',
    province: 'นครปฐม',
    position: 'FW',
    ovr: 67,
    pts: 1255,
    pac: 76,
    sho: 69,
    pas: 55,
    dri: 68,
    def: 36,
    rank_change: -7,
    sport: 'football',
    season: '2026',
  },
]

export const sampleTournaments = [
  {
    id: 'sample-tournament-1',
    name: 'BALLSAI Youth Cup 2026',
    description: 'รายการเยาวชนรุ่นอายุไม่เกิน 16 ปี ใช้ผลแข่งอัปเดต Power Rating',
    location: 'สนามกีฬาเฉลิมพระเกียรติ อยุธยา',
    start_date: '2026-07-12',
    end_date: '2026-07-12',
    fee: 500,
    promptpay: '0812345678',
    max_teams: 16,
    status: 'open',
    organizer_id: 'sample-organizer',
  },
  {
    id: 'sample-tournament-2',
    name: 'Bangkok Futsal Challenge',
    description: 'บอลเดินสายฟุตซอล 5 คน พร้อมบันทึก MVP และสถิติรายคน',
    location: 'สนามฟุตซอลพระราม 9',
    start_date: '2026-07-26',
    end_date: '2026-07-27',
    fee: 800,
    promptpay: '0899991111',
    max_teams: 24,
    status: 'open',
    organizer_id: 'sample-organizer',
  },
  {
    id: 'sample-tournament-3',
    name: 'Eastern Rising Stars',
    description: 'ทัวร์นาเมนต์ภาคตะวันออกสำหรับทีมเยาวชนหน้าใหม่',
    location: 'ชลบุรี อารีนา',
    start_date: '2026-08-09',
    end_date: '2026-08-09',
    fee: 650,
    promptpay: '0865552222',
    max_teams: 20,
    status: 'open',
    organizer_id: 'sample-organizer',
  },
]

export const showDemoData = process.env.NEXT_PUBLIC_SHOW_DEMO_DATA === 'true'

export function isSampleId(id: string) {
  return id.startsWith('sample-')
}
