-- READ-ONLY inventory: which migration files have left their fingerprint in this database.
-- Generated from sql/ on main at 970731a+e58e2ac plus the 8 SQL files that exist only on
-- codex/player-card-beta (marked [beta]). Reads the system catalog only (pg_proc, pg_class,
-- information_schema.columns, pg_trigger, pg_policies, pg_indexes). It reads no table rows
-- and no user data, and changes nothing.
--
-- BEFORE RUNNING: confirm the Supabase dashboard URL shows the project you mean.
--   Production: hivedzrwrrcnjrlirhtv   Staging: vorpnkedpscsqhnrssrl
-- Run it on both and compare; save each result with the project ref and date.
--
-- A file's fingerprint is the set of objects it creates that no other file creates.
-- found = total  -> the file's objects exist (applied, or the same objects came from elsewhere)
-- found = 0      -> not applied
-- 0 < found < total -> partly applied, or edited by hand: investigate before any change
-- Files with no unique object (privilege/grant-only changes, or objects shared with other
-- files) cannot be detected here: 19-notification-team-member-privilege-hardening-v1.sql, 22-guardian-consent-trigger-v1.sql, 24-venue-owner-onboarding-v1.sql, 33-data-deletion-function-privilege-hardening-v1.sql, 36-data-deletion-search-path-hardening-v1.sql, 37-quarantine-legacy-payment-slip-links-v1.sql, 38-close-venue-slot-v1.sql, 39-venue-rpc-privilege-hardening-v1.sql, 42-notification-privilege-hardening-v1.sql, 44-venue-photo-storage-policy-fix-v1.sql, 45-venue-photo-public-delivery-v1.sql, [beta] 23-mobile-onboarding-execute-grants-v1.sql, [beta] 26-team-function-privileges-v1.sql, guardian-consent-enforcement-v1.sql.

with expected(file, kind, name, extra) as (values
  ('17-notifications-v1.sql', 'function', 'create_notification', ''),
  ('17-notifications-v1.sql', 'function', 'notify_badge_earned', ''),
  ('17-notifications-v1.sql', 'function', 'notify_match_result_created', ''),
  ('17-notifications-v1.sql', 'function', 'notify_team_status_changed', ''),
  ('17-notifications-v1.sql', 'index', 'notifications_user_created_idx', ''),
  ('17-notifications-v1.sql', 'index', 'notifications_user_unread_idx', ''),
  ('17-notifications-v1.sql', 'policy', 'notifications_owner_select', 'notifications'),
  ('17-notifications-v1.sql', 'policy', 'notifications_owner_update', 'notifications'),
  ('17-notifications-v1.sql', 'table', 'notifications', ''),
  ('17-notifications-v1.sql', 'trigger', 'athlete_badge_notify_earned', ''),
  ('17-notifications-v1.sql', 'trigger', 'match_result_notify_created', ''),
  ('17-notifications-v1.sql', 'trigger', 'team_notify_status_changed', ''),
  ('18-team-members-v1.sql', 'index', 'team_members_athlete_status_idx', ''),
  ('18-team-members-v1.sql', 'policy', 'team_members_update_member_or_owner', 'team_members'),
  ('18-team-members-v1.sql', 'table', 'team_members', ''),
  ('20-tournament-roster-flow-v1.sql', 'function', 'assert_match_performance_roster_member', ''),
  ('20-tournament-roster-flow-v1.sql', 'function', 'assert_payment_team_is_pending', ''),
  ('20-tournament-roster-flow-v1.sql', 'function', 'create_tournament_team_safely', ''),
  ('20-tournament-roster-flow-v1.sql', 'function', 'submit_tournament_team_safely', ''),
  ('20-tournament-roster-flow-v1.sql', 'index', 'teams_tournament_draft_idx', ''),
  ('20-tournament-roster-flow-v1.sql', 'trigger', 'match_performance_roster_guard', ''),
  ('20-tournament-roster-flow-v1.sql', 'trigger', 'payment_team_pending_guard', ''),
  ('21-guardian-links-v1.sql', 'function', 'is_accepted_guardian_for', ''),
  ('21-guardian-links-v1.sql', 'function', 'request_guardian_link', ''),
  ('21-guardian-links-v1.sql', 'function', 'respond_guardian_link', ''),
  ('21-guardian-links-v1.sql', 'function', 'revoke_guardian_link', ''),
  ('21-guardian-links-v1.sql', 'index', 'guardian_links_athlete_status_idx', ''),
  ('21-guardian-links-v1.sql', 'index', 'guardian_links_guardian_status_idx', ''),
  ('21-guardian-links-v1.sql', 'table', 'guardian_links', ''),
  ('23-venues-and-bookings-v1.sql', 'function', 'create_venue_court_safely', ''),
  ('23-venues-and-bookings-v1.sql', 'function', 'create_venue_profile_safely', ''),
  ('23-venues-and-bookings-v1.sql', 'function', 'create_venue_slot_safely', ''),
  ('23-venues-and-bookings-v1.sql', 'index', 'venue_booking_requests_live_slot_idx', ''),
  ('23-venues-and-bookings-v1.sql', 'index', 'venue_booking_requests_requester_idx', ''),
  ('23-venues-and-bookings-v1.sql', 'index', 'venue_courts_venue_idx', ''),
  ('23-venues-and-bookings-v1.sql', 'index', 'venue_profiles_owner_idx', ''),
  ('23-venues-and-bookings-v1.sql', 'index', 'venue_profiles_published_province_idx', ''),
  ('23-venues-and-bookings-v1.sql', 'index', 'venue_slots_court_time_idx', ''),
  ('23-venues-and-bookings-v1.sql', 'table', 'venue_booking_requests', ''),
  ('23-venues-and-bookings-v1.sql', 'table', 'venue_courts', ''),
  ('23-venues-and-bookings-v1.sql', 'table', 'venue_profiles', ''),
  ('23-venues-and-bookings-v1.sql', 'table', 'venue_slots', ''),
  ('25-scout-shortlists-v1.sql', 'function', 'add_scout_shortlist_safely', ''),
  ('25-scout-shortlists-v1.sql', 'function', 'remove_scout_shortlist_safely', ''),
  ('25-scout-shortlists-v1.sql', 'index', 'scout_shortlists_athlete_idx', ''),
  ('25-scout-shortlists-v1.sql', 'index', 'scout_shortlists_scout_created_idx', ''),
  ('25-scout-shortlists-v1.sql', 'table', 'scout_shortlists', ''),
  ('26-organizations-v1.sql', 'function', 'create_organization_safely', ''),
  ('26-organizations-v1.sql', 'function', 'create_organization_team_safely', ''),
  ('26-organizations-v1.sql', 'function', 'invite_organization_member_safely', ''),
  ('26-organizations-v1.sql', 'function', 'is_organization_member', ''),
  ('26-organizations-v1.sql', 'function', 'respond_organization_invite_safely', ''),
  ('26-organizations-v1.sql', 'index', 'organization_members_org_idx', ''),
  ('26-organizations-v1.sql', 'index', 'organization_members_user_idx', ''),
  ('26-organizations-v1.sql', 'index', 'organization_teams_org_idx', ''),
  ('26-organizations-v1.sql', 'table', 'organization_members', ''),
  ('26-organizations-v1.sql', 'table', 'organization_teams', ''),
  ('26-organizations-v1.sql', 'table', 'organizations', ''),
  ('27-sponsor-brand-opportunities-v1.sql', 'function', 'create_sponsor_profile_safely', ''),
  ('27-sponsor-brand-opportunities-v1.sql', 'function', 'create_sponsorship_opportunity_safely', ''),
  ('27-sponsor-brand-opportunities-v1.sql', 'function', 'express_sponsorship_interest_safely', ''),
  ('27-sponsor-brand-opportunities-v1.sql', 'index', 'sponsorship_interests_athlete_idx', ''),
  ('27-sponsor-brand-opportunities-v1.sql', 'index', 'sponsorship_interests_opportunity_idx', ''),
  ('27-sponsor-brand-opportunities-v1.sql', 'index', 'sponsorship_opportunities_public_idx', ''),
  ('27-sponsor-brand-opportunities-v1.sql', 'index', 'sponsorship_opportunities_sponsor_idx', ''),
  ('27-sponsor-brand-opportunities-v1.sql', 'table', 'sponsor_profiles', ''),
  ('27-sponsor-brand-opportunities-v1.sql', 'table', 'sponsorship_interests', ''),
  ('27-sponsor-brand-opportunities-v1.sql', 'table', 'sponsorship_opportunities', ''),
  ('28-match-plans-v1.sql', 'function', 'get_match_plan_safely', ''),
  ('28-match-plans-v1.sql', 'function', 'save_match_plan_safely', ''),
  ('28-match-plans-v1.sql', 'function', 'set_match_plan_updated_at', ''),
  ('28-match-plans-v1.sql', 'index', 'match_plan_players_plan_slot_idx', ''),
  ('28-match-plans-v1.sql', 'table', 'match_plan_players', ''),
  ('28-match-plans-v1.sql', 'table', 'match_plans', ''),
  ('28-match-plans-v1.sql', 'trigger', 'match_plans_set_updated_at', ''),
  ('29-bds-wallet-v1.sql', 'function', 'award_bds_points_safely', ''),
  ('29-bds-wallet-v1.sql', 'index', 'bds_transactions_user_created_idx', ''),
  ('29-bds-wallet-v1.sql', 'policy', 'bds_transaction_owner_or_admin', 'bds_transactions'),
  ('29-bds-wallet-v1.sql', 'policy', 'bds_wallet_owner_or_admin', 'bds_wallets'),
  ('29-bds-wallet-v1.sql', 'table', 'bds_transactions', ''),
  ('29-bds-wallet-v1.sql', 'table', 'bds_wallets', ''),
  ('30-bds-match-rewards-v1.sql', 'function', 'award_bds_from_rating_event', ''),
  ('30-bds-match-rewards-v1.sql', 'trigger', 'rating_event_award_bds', ''),
  ('31-data-trust-foundation-v1.sql', 'function', 'can_view_verification_event_subject', ''),
  ('31-data-trust-foundation-v1.sql', 'function', 'open_data_dispute_safely', ''),
  ('31-data-trust-foundation-v1.sql', 'function', 'resolve_data_dispute_safely', ''),
  ('31-data-trust-foundation-v1.sql', 'index', 'data_anomaly_flags_queue_idx', ''),
  ('31-data-trust-foundation-v1.sql', 'index', 'data_disputes_opened_by_idx', ''),
  ('31-data-trust-foundation-v1.sql', 'index', 'data_disputes_queue_idx', ''),
  ('31-data-trust-foundation-v1.sql', 'index', 'data_provenance_subject_idx', ''),
  ('31-data-trust-foundation-v1.sql', 'index', 'rank_explanations_player_idx', ''),
  ('31-data-trust-foundation-v1.sql', 'index', 'verification_events_subject_idx', ''),
  ('31-data-trust-foundation-v1.sql', 'index', 'verification_evidence_provenance_idx', ''),
  ('31-data-trust-foundation-v1.sql', 'table', 'data_anomaly_flags', ''),
  ('31-data-trust-foundation-v1.sql', 'table', 'data_disputes', ''),
  ('31-data-trust-foundation-v1.sql', 'table', 'data_provenance', ''),
  ('31-data-trust-foundation-v1.sql', 'table', 'rank_explanations', ''),
  ('31-data-trust-foundation-v1.sql', 'table', 'verification_events', ''),
  ('31-data-trust-foundation-v1.sql', 'table', 'verification_evidence', ''),
  ('31-data-trust-foundation-v1.sql', 'trigger', 'verification_events_append_only', ''),
  ('32-bds-void-reversal-v1.sql', 'column', 'bds_transactions', 'reverses_transaction_id'),
  ('32-bds-void-reversal-v1.sql', 'column', 'bds_transactions', 'source_rating_event_id'),
  ('32-bds-void-reversal-v1.sql', 'function', 'reverse_bds_for_deleted_rating_event', ''),
  ('32-bds-void-reversal-v1.sql', 'index', 'bds_reversal_holds_queue_idx', ''),
  ('32-bds-void-reversal-v1.sql', 'index', 'bds_reversal_holds_user_idx', ''),
  ('32-bds-void-reversal-v1.sql', 'index', 'bds_transactions_one_reversal_idx', ''),
  ('32-bds-void-reversal-v1.sql', 'index', 'bds_transactions_source_rating_event_idx', ''),
  ('32-bds-void-reversal-v1.sql', 'table', 'bds_reversal_holds', ''),
  ('32-bds-void-reversal-v1.sql', 'trigger', 'rating_event_bds_void_reversal', ''),
  ('34-admin-command-center-performance-v1.sql', 'function', 'get_admin_command_center_summary', ''),
  ('34-admin-command-center-performance-v1.sql', 'index', 'athlete_profiles_display_name_trgm_idx', ''),
  ('34-admin-command-center-performance-v1.sql', 'index', 'guardian_links_admin_pending_queue_idx', ''),
  ('34-admin-command-center-performance-v1.sql', 'index', 'organization_members_admin_pending_queue_idx', ''),
  ('34-admin-command-center-performance-v1.sql', 'index', 'payments_admin_unconfirmed_queue_idx', ''),
  ('34-admin-command-center-performance-v1.sql', 'index', 'profiles_role_admin_summary_idx', ''),
  ('34-admin-command-center-performance-v1.sql', 'index', 'sponsorship_interests_admin_submitted_queue_idx', ''),
  ('34-admin-command-center-performance-v1.sql', 'index', 'teams_admin_pending_queue_idx', ''),
  ('34-admin-command-center-performance-v1.sql', 'index', 'venue_bookings_admin_pending_queue_idx', ''),
  ('35-admin-audit-log-v1.sql', 'function', 'admin_award_hall_entry_with_audit', ''),
  ('35-admin-audit-log-v1.sql', 'function', 'admin_create_player_rank_with_audit', ''),
  ('35-admin-audit-log-v1.sql', 'function', 'admin_delete_player_rank_with_audit', ''),
  ('35-admin-audit-log-v1.sql', 'function', 'admin_resolve_data_dispute_with_audit', ''),
  ('35-admin-audit-log-v1.sql', 'function', 'admin_update_player_rank_with_audit', ''),
  ('35-admin-audit-log-v1.sql', 'function', 'record_admin_audit_event', ''),
  ('35-admin-audit-log-v1.sql', 'index', 'admin_audit_logs_action_created_idx', ''),
  ('35-admin-audit-log-v1.sql', 'index', 'admin_audit_logs_actor_created_idx', ''),
  ('35-admin-audit-log-v1.sql', 'index', 'admin_audit_logs_created_idx', ''),
  ('35-admin-audit-log-v1.sql', 'index', 'admin_audit_logs_target_created_idx', ''),
  ('35-admin-audit-log-v1.sql', 'policy', 'admin_audit_logs_admin_select', 'admin_audit_logs'),
  ('35-admin-audit-log-v1.sql', 'table', 'admin_audit_logs', ''),
  ('40-venue-slot-booking-state-v1.sql', 'column', 'venue_booking_requests', 'court_name_snapshot'),
  ('40-venue-slot-booking-state-v1.sql', 'column', 'venue_booking_requests', 'price_baht_snapshot'),
  ('40-venue-slot-booking-state-v1.sql', 'column', 'venue_booking_requests', 'slot_ends_at_snapshot'),
  ('40-venue-slot-booking-state-v1.sql', 'column', 'venue_booking_requests', 'slot_starts_at_snapshot'),
  ('40-venue-slot-booking-state-v1.sql', 'column', 'venue_booking_requests', 'venue_name_snapshot'),
  ('41-venue-booking-notifications-v1.sql', 'function', 'notify_venue_booking_requested', ''),
  ('41-venue-booking-notifications-v1.sql', 'function', 'notify_venue_booking_responded', ''),
  ('41-venue-booking-notifications-v1.sql', 'trigger', 'venue_booking_notify_requested', ''),
  ('41-venue-booking-notifications-v1.sql', 'trigger', 'venue_booking_notify_responded', ''),
  ('43-venue-photos-v1.sql', 'function', 'add_venue_photo_safely', ''),
  ('43-venue-photos-v1.sql', 'function', 'moderate_venue_photo_safely', ''),
  ('43-venue-photos-v1.sql', 'function', 'remove_venue_photo_safely', ''),
  ('43-venue-photos-v1.sql', 'function', 'reorder_venue_photos_safely', ''),
  ('43-venue-photos-v1.sql', 'function', 'set_venue_photo_cover_safely', ''),
  ('43-venue-photos-v1.sql', 'index', 'venue_photos_moderation_queue_idx', ''),
  ('43-venue-photos-v1.sql', 'index', 'venue_photos_one_cover_idx', ''),
  ('43-venue-photos-v1.sql', 'index', 'venue_photos_venue_order_idx', ''),
  ('43-venue-photos-v1.sql', 'table', 'venue_photos', ''),
  ('46-venue-beta-operations-v1.sql', 'function', 'coordinate_venue_booking_beta', ''),
  ('46-venue-beta-operations-v1.sql', 'function', 'guard_venue_slot_overlap_beta', ''),
  ('46-venue-beta-operations-v1.sql', 'function', 'manage_venue_beta', ''),
  ('46-venue-beta-operations-v1.sql', 'function', 'venue_booking_options_beta', ''),
  ('46-venue-beta-operations-v1.sql', 'function', 'venue_booking_participant_beta', ''),
  ('46-venue-beta-operations-v1.sql', 'index', 'venue_coordination_booking_idx', ''),
  ('46-venue-beta-operations-v1.sql', 'index', 'venue_coordination_pending_idx', ''),
  ('46-venue-beta-operations-v1.sql', 'table', 'venue_booking_coordination', ''),
  ('46-venue-beta-operations-v1.sql', 'trigger', 'venue_slot_overlap_beta', ''),
  ('47-coach-beta-management-v1.sql', 'function', 'attest_coach_claim_beta', ''),
  ('47-coach-beta-management-v1.sql', 'function', 'is_team_creator_beta', ''),
  ('47-coach-beta-management-v1.sql', 'function', 'manage_coach_beta', ''),
  ('47-coach-beta-management-v1.sql', 'function', 'respond_coach_attestation_beta', ''),
  ('47-coach-beta-management-v1.sql', 'index', 'coach_attestations_athlete_idx', ''),
  ('47-coach-beta-management-v1.sql', 'index', 'coach_attestations_live_idx', ''),
  ('47-coach-beta-management-v1.sql', 'index', 'coach_attestations_team_idx', ''),
  ('47-coach-beta-management-v1.sql', 'index', 'coach_verified_fields_athlete_idx', ''),
  ('47-coach-beta-management-v1.sql', 'table', 'coach_attestations', ''),
  ('47-coach-beta-management-v1.sql', 'table', 'coach_verified_fields', ''),
  ('athlete-highlight-uploads-v1.sql', 'index', 'athlete_highlights_athlete_created_idx', ''),
  ('athlete-highlight-uploads-v1.sql', 'policy', 'athlete_highlights_owner_delete', 'objects'),
  ('athlete-highlight-uploads-v1.sql', 'policy', 'athlete_highlights_owner_insert', 'objects'),
  ('athlete-highlight-uploads-v1.sql', 'policy', 'athlete_highlights_owner_write', 'athlete_highlights'),
  ('athlete-highlight-uploads-v1.sql', 'table', 'athlete_highlights', ''),
  ('athlete-profile-v2.sql', 'function', 'set_athlete_profile_updated_at', ''),
  ('athlete-profile-v2.sql', 'index', 'athlete_achievements_athlete_id_idx', ''),
  ('athlete-profile-v2.sql', 'index', 'athlete_profiles_discovery_idx', ''),
  ('athlete-profile-v2.sql', 'index', 'athlete_skill_assessments_athlete_id_idx', ''),
  ('athlete-profile-v2.sql', 'index', 'athlete_videos_athlete_id_idx', ''),
  ('athlete-profile-v2.sql', 'policy', 'athlete_achievements_owner_write', 'athlete_achievements'),
  ('athlete-profile-v2.sql', 'policy', 'athlete_achievements_public_or_owner_select', 'athlete_achievements'),
  ('athlete-profile-v2.sql', 'policy', 'athlete_avatars_owner_delete', 'objects'),
  ('athlete-profile-v2.sql', 'policy', 'athlete_avatars_owner_insert', 'objects'),
  ('athlete-profile-v2.sql', 'policy', 'athlete_avatars_owner_update', 'objects'),
  ('athlete-profile-v2.sql', 'policy', 'athlete_avatars_public_read', 'objects'),
  ('athlete-profile-v2.sql', 'policy', 'athlete_profiles_owner_insert', 'athlete_profiles'),
  ('athlete-profile-v2.sql', 'policy', 'athlete_profiles_owner_update', 'athlete_profiles'),
  ('athlete-profile-v2.sql', 'policy', 'athlete_profiles_public_or_owner_select', 'athlete_profiles'),
  ('athlete-profile-v2.sql', 'policy', 'athlete_skills_public_or_owner_select', 'athlete_skill_assessments'),
  ('athlete-profile-v2.sql', 'policy', 'athlete_skills_self_insert', 'athlete_skill_assessments'),
  ('athlete-profile-v2.sql', 'policy', 'athlete_videos_owner_write', 'athlete_videos'),
  ('athlete-profile-v2.sql', 'policy', 'athlete_videos_public_or_owner_select', 'athlete_videos'),
  ('athlete-profile-v2.sql', 'table', 'athlete_achievements', ''),
  ('athlete-profile-v2.sql', 'table', 'athlete_profiles', ''),
  ('athlete-profile-v2.sql', 'table', 'athlete_skill_assessments', ''),
  ('athlete-profile-v2.sql', 'table', 'athlete_videos', ''),
  ('athlete-profile-v2.sql', 'trigger', 'athlete_profiles_set_updated_at', ''),
  ('ballsai-rating-v1.sql', 'index', 'match_player_performances_match_idx', ''),
  ('ballsai-rating-v1.sql', 'index', 'match_results_tournament_created_idx', ''),
  ('ballsai-rating-v1.sql', 'index', 'player_ratings_sport_season_rating_idx', ''),
  ('ballsai-rating-v1.sql', 'index', 'rating_events_player_rating_created_idx', ''),
  ('ballsai-rating-v1.sql', 'policy', 'match_player_performances_organizer_write', 'match_player_performances'),
  ('ballsai-rating-v1.sql', 'policy', 'match_player_performances_select_public', 'match_player_performances'),
  ('ballsai-rating-v1.sql', 'policy', 'match_results_organizer_write', 'match_results'),
  ('ballsai-rating-v1.sql', 'policy', 'match_results_select_public', 'match_results'),
  ('ballsai-rating-v1.sql', 'policy', 'player_ratings_admin_write', 'player_ratings'),
  ('ballsai-rating-v1.sql', 'policy', 'player_ratings_select_public', 'player_ratings'),
  ('ballsai-rating-v1.sql', 'policy', 'rating_events_admin_write', 'rating_events'),
  ('ballsai-rating-v1.sql', 'policy', 'rating_events_select_public', 'rating_events'),
  ('ballsai-rating-v1.sql', 'table', 'match_player_performances', ''),
  ('ballsai-rating-v1.sql', 'table', 'match_results', ''),
  ('ballsai-rating-v1.sql', 'table', 'player_ratings', ''),
  ('ballsai-rating-v1.sql', 'table', 'rating_events', ''),
  ('[beta] 19-athlete-sport-profiles-v1.sql', 'function', 'enforce_legacy_guardian_consent_for_sport_profile', ''),
  ('[beta] 19-athlete-sport-profiles-v1.sql', 'function', 'set_athlete_sport_profile_updated_at', ''),
  ('[beta] 19-athlete-sport-profiles-v1.sql', 'index', 'athlete_sport_profiles_athlete_status_idx', ''),
  ('[beta] 19-athlete-sport-profiles-v1.sql', 'index', 'athlete_sport_profiles_public_discovery_idx', ''),
  ('[beta] 19-athlete-sport-profiles-v1.sql', 'policy', 'athlete_sport_profiles_owner_insert', 'athlete_sport_profiles'),
  ('[beta] 19-athlete-sport-profiles-v1.sql', 'policy', 'athlete_sport_profiles_owner_or_admin_update', 'athlete_sport_profiles'),
  ('[beta] 19-athlete-sport-profiles-v1.sql', 'policy', 'athlete_sport_profiles_public_or_owner_select', 'athlete_sport_profiles'),
  ('[beta] 19-athlete-sport-profiles-v1.sql', 'table', 'athlete_sport_profiles', ''),
  ('[beta] 19-athlete-sport-profiles-v1.sql', 'trigger', 'athlete_sport_profiles_set_updated_at', ''),
  ('[beta] 20-guardian-verification-v2.sql', 'function', 'cancel_guardian_verification', ''),
  ('[beta] 20-guardian-verification-v2.sql', 'function', 'confirm_guardian_verification', ''),
  ('[beta] 20-guardian-verification-v2.sql', 'function', 'enforce_guardian_consent_for_public_sport_profile', ''),
  ('[beta] 20-guardian-verification-v2.sql', 'function', 'has_active_guardian_consent', ''),
  ('[beta] 20-guardian-verification-v2.sql', 'function', 'request_guardian_verification', ''),
  ('[beta] 20-guardian-verification-v2.sql', 'function', 'revoke_guardian_consent', ''),
  ('[beta] 20-guardian-verification-v2.sql', 'index', 'guardian_consent_events_athlete_created_idx', ''),
  ('[beta] 20-guardian-verification-v2.sql', 'index', 'guardian_consent_events_request_created_idx', ''),
  ('[beta] 20-guardian-verification-v2.sql', 'index', 'guardian_consents_one_active_idx', ''),
  ('[beta] 20-guardian-verification-v2.sql', 'index', 'guardian_consents_revocation_token_idx', ''),
  ('[beta] 20-guardian-verification-v2.sql', 'index', 'guardian_verification_athlete_status_idx', ''),
  ('[beta] 20-guardian-verification-v2.sql', 'index', 'guardian_verification_one_pending_idx', ''),
  ('[beta] 20-guardian-verification-v2.sql', 'index', 'guardian_verification_token_idx', ''),
  ('[beta] 20-guardian-verification-v2.sql', 'policy', 'guardian_consents_owner_or_admin_select', 'guardian_consents'),
  ('[beta] 20-guardian-verification-v2.sql', 'policy', 'guardian_events_owner_or_admin_select', 'guardian_consent_events'),
  ('[beta] 20-guardian-verification-v2.sql', 'policy', 'guardian_requests_owner_or_admin_select', 'guardian_verification_requests'),
  ('[beta] 20-guardian-verification-v2.sql', 'table', 'guardian_consent_events', ''),
  ('[beta] 20-guardian-verification-v2.sql', 'table', 'guardian_consents', ''),
  ('[beta] 20-guardian-verification-v2.sql', 'table', 'guardian_verification_requests', ''),
  ('[beta] 21-sport-scoped-identity-v1.sql', 'function', 'create_sport_starter_identity', ''),
  ('[beta] 21-sport-scoped-identity-v1.sql', 'function', 'sync_athlete_sport_identity_from_rating_event', ''),
  ('[beta] 21-sport-scoped-identity-v1.sql', 'index', 'athlete_sport_badges_athlete_awarded_idx', ''),
  ('[beta] 21-sport-scoped-identity-v1.sql', 'index', 'athlete_sport_xp_events_athlete_created_idx', ''),
  ('[beta] 21-sport-scoped-identity-v1.sql', 'policy', 'sport_badges_public_or_owner_select', 'athlete_sport_badges'),
  ('[beta] 21-sport-scoped-identity-v1.sql', 'policy', 'sport_progress_public_or_owner_select', 'athlete_sport_progress'),
  ('[beta] 21-sport-scoped-identity-v1.sql', 'policy', 'sport_xp_events_owner_or_admin_select', 'athlete_sport_xp_events'),
  ('[beta] 21-sport-scoped-identity-v1.sql', 'table', 'athlete_sport_badges', ''),
  ('[beta] 21-sport-scoped-identity-v1.sql', 'table', 'athlete_sport_progress', ''),
  ('[beta] 21-sport-scoped-identity-v1.sql', 'table', 'athlete_sport_xp_events', ''),
  ('[beta] 21-sport-scoped-identity-v1.sql', 'trigger', 'athlete_sport_profile_create_starter_identity', ''),
  ('[beta] 21-sport-scoped-identity-v1.sql', 'trigger', 'rating_event_sync_athlete_sport_identity', ''),
  ('[beta] 22-mobile-onboarding-v1.sql', 'function', 'complete_mobile_onboarding', ''),
  ('[beta] 24-team-roster-integrity-v1.sql', 'column', 'match_player_performances', 'membership_verified_at'),
  ('[beta] 24-team-roster-integrity-v1.sql', 'column', 'match_player_performances', 'team_membership_id'),
  ('[beta] 24-team-roster-integrity-v1.sql', 'column', 'team_members', 'accepted_at'),
  ('[beta] 24-team-roster-integrity-v1.sql', 'column', 'team_members', 'direction'),
  ('[beta] 24-team-roster-integrity-v1.sql', 'column', 'team_members', 'removed_at'),
  ('[beta] 24-team-roster-integrity-v1.sql', 'column', 'team_members', 'removed_by'),
  ('[beta] 24-team-roster-integrity-v1.sql', 'column', 'team_members', 'removed_reason'),
  ('[beta] 24-team-roster-integrity-v1.sql', 'function', 'approve_team_request', ''),
  ('[beta] 24-team-roster-integrity-v1.sql', 'function', 'decline_team_request', ''),
  ('[beta] 24-team-roster-integrity-v1.sql', 'function', 'remove_team_member', ''),
  ('[beta] 24-team-roster-integrity-v1.sql', 'index', 'match_player_performances_membership_idx', ''),
  ('[beta] 24-team-roster-integrity-v1.sql', 'index', 'team_members_one_active_period_idx', ''),
  ('[beta] 25-team-discovery-v1.sql', 'function', 'list_joinable_teams', ''),
  ('[beta] 25-team-discovery-v1.sql', 'function', 'list_my_team_labels', ''),
  ('data-deletion-v1.sql', 'index', 'account_deletion_requests_open_idx', ''),
  ('data-deletion-v1.sql', 'policy', 'deletion_requests_admin_update', 'account_deletion_requests'),
  ('data-deletion-v1.sql', 'policy', 'deletion_requests_owner_or_admin_select', 'account_deletion_requests'),
  ('data-deletion-v1.sql', 'table', 'account_deletion_requests', ''),
  ('digital-identity-v1.sql', 'function', 'sync_athlete_identity_from_rating_event', ''),
  ('digital-identity-v1.sql', 'index', 'athlete_badges_athlete_awarded_idx', ''),
  ('digital-identity-v1.sql', 'index', 'athlete_xp_events_athlete_created_idx', ''),
  ('digital-identity-v1.sql', 'policy', 'identity_badges_public_or_owner_select', 'athlete_badges'),
  ('digital-identity-v1.sql', 'policy', 'identity_progress_public_or_owner_select', 'athlete_progress'),
  ('digital-identity-v1.sql', 'policy', 'identity_xp_owner_or_admin_select', 'athlete_xp_events'),
  ('digital-identity-v1.sql', 'table', 'athlete_badges', ''),
  ('digital-identity-v1.sql', 'table', 'athlete_progress', ''),
  ('digital-identity-v1.sql', 'table', 'athlete_xp_events', ''),
  ('digital-identity-v1.sql', 'trigger', 'rating_event_sync_athlete_identity', ''),
  ('digital-identity-v2-hall.sql', 'column', 'athlete_achievements', 'identity_badge_key'),
  ('digital-identity-v2-hall.sql', 'function', 'create_rookie_identity', ''),
  ('digital-identity-v2-hall.sql', 'function', 'sync_identity_badge_achievement', ''),
  ('digital-identity-v2-hall.sql', 'index', 'athlete_achievements_identity_badge_idx', ''),
  ('digital-identity-v2-hall.sql', 'index', 'hall_of_fame_athlete_idx', ''),
  ('digital-identity-v2-hall.sql', 'index', 'hall_of_fame_browse_idx', ''),
  ('digital-identity-v2-hall.sql', 'policy', 'hall_of_fame_organizer_write', 'hall_of_fame_entries'),
  ('digital-identity-v2-hall.sql', 'policy', 'hall_of_fame_public_select', 'hall_of_fame_entries'),
  ('digital-identity-v2-hall.sql', 'table', 'hall_of_fame_entries', ''),
  ('digital-identity-v2-hall.sql', 'trigger', 'athlete_badge_sync_achievement', ''),
  ('digital-identity-v2-hall.sql', 'trigger', 'athlete_profile_create_rookie_identity', ''),
  ('fix-profile-auth-trigger.sql', 'column', 'profiles', 'updated_at'),
  ('fix-profile-auth-trigger.sql', 'function', 'handle_new_user', ''),
  ('fix-profile-auth-trigger.sql', 'trigger', 'on_auth_user_created', ''),
  ('highlight-moderation-v1.sql', 'column', 'athlete_highlights', 'hidden_at'),
  ('highlight-moderation-v1.sql', 'column', 'athlete_highlights', 'hidden_by'),
  ('highlight-moderation-v1.sql', 'column', 'athlete_highlights', 'moderation_status'),
  ('highlight-moderation-v1.sql', 'index', 'athlete_highlight_reports_highlight_idx', ''),
  ('highlight-moderation-v1.sql', 'index', 'athlete_highlight_reports_open_idx', ''),
  ('highlight-moderation-v1.sql', 'index', 'athlete_highlights_hidden_idx', ''),
  ('highlight-moderation-v1.sql', 'policy', 'highlight_reports_admin_delete', 'athlete_highlight_reports'),
  ('highlight-moderation-v1.sql', 'policy', 'highlight_reports_admin_update', 'athlete_highlight_reports'),
  ('highlight-moderation-v1.sql', 'policy', 'highlight_reports_reporter_insert', 'athlete_highlight_reports'),
  ('highlight-moderation-v1.sql', 'policy', 'highlight_reports_reporter_or_admin_select', 'athlete_highlight_reports'),
  ('highlight-moderation-v1.sql', 'table', 'athlete_highlight_reports', ''),
  ('link-player-ranks-to-profiles.sql', 'column', 'player_ranks', 'player_id'),
  ('match-result-void-v1.sql', 'function', 'void_match_result_safely', ''),
  ('match-result-void-v1.sql', 'index', 'rating_events_match_id_idx', ''),
  ('onboarding-v1.sql', 'column', 'profiles', 'onboarding_completed_at'),
  ('onboarding-v1.sql', 'column', 'profiles', 'onboarding_goal'),
  ('onboarding-v1.sql', 'column', 'profiles', 'onboarding_persona'),
  ('onboarding-v1.sql', 'column', 'profiles', 'onboarding_sport'),
  ('onboarding-v1.sql', 'index', 'profiles_onboarding_persona_idx', ''),
  ('production-hardening.sql', 'function', 'confirm_payment_safely', ''),
  ('production-hardening.sql', 'function', 'register_team_safely', ''),
  ('production-hardening.sql', 'index', 'payments_slip_url_idx', ''),
  ('production-hardening.sql', 'index', 'player_ranks_public_ranking_idx', ''),
  ('production-hardening.sql', 'index', 'teams_creator_created_at_idx', ''),
  ('production-hardening.sql', 'index', 'tournaments_open_start_date_idx', ''),
  ('production-hardening.sql', 'policy', 'slips_read_owner_organizer_admin', 'objects'),
  ('supabase-rls.sql', 'function', 'is_admin', ''),
  ('supabase-rls.sql', 'function', 'is_organizer', ''),
  ('supabase-rls.sql', 'index', 'payments_one_payment_per_team_idx', ''),
  ('supabase-rls.sql', 'index', 'payments_tournament_id_idx', ''),
  ('supabase-rls.sql', 'index', 'teams_one_registration_per_user_per_tournament_idx', ''),
  ('supabase-rls.sql', 'index', 'teams_tournament_id_idx', ''),
  ('supabase-rls.sql', 'index', 'tournaments_organizer_id_idx', ''),
  ('supabase-rls.sql', 'policy', 'payments_insert_owner_for_own_team', 'payments'),
  ('supabase-rls.sql', 'policy', 'payments_select_owner_organizer_admin', 'payments'),
  ('supabase-rls.sql', 'policy', 'payments_update_organizer_admin', 'payments'),
  ('supabase-rls.sql', 'policy', 'player_ranks_admin_delete', 'player_ranks'),
  ('supabase-rls.sql', 'policy', 'player_ranks_admin_insert', 'player_ranks'),
  ('supabase-rls.sql', 'policy', 'player_ranks_admin_update', 'player_ranks'),
  ('supabase-rls.sql', 'policy', 'player_ranks_select_public', 'player_ranks'),
  ('supabase-rls.sql', 'policy', 'slips_owner_delete', 'objects'),
  ('supabase-rls.sql', 'policy', 'slips_owner_insert', 'objects'),
  ('supabase-rls.sql', 'policy', 'slips_public_read', 'objects'),
  ('supabase-rls.sql', 'policy', 'teams_insert_creator_for_open_tournament', 'teams'),
  ('supabase-rls.sql', 'policy', 'teams_select_owner_organizer_admin', 'teams'),
  ('supabase-rls.sql', 'policy', 'teams_update_organizer_admin', 'teams'),
  ('supabase-rls.sql', 'policy', 'tournaments_insert_organizer', 'tournaments'),
  ('supabase-rls.sql', 'policy', 'tournaments_select_public', 'tournaments'),
  ('supabase-rls.sql', 'policy', 'tournaments_update_owner_or_admin', 'tournaments')
),
checked as (
  select e.*,
    case e.kind
      when 'function' then exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = e.name)
      when 'table'    then exists (select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace where n.nspname = 'public' and c.relname = e.name)
      when 'column'   then exists (select 1 from information_schema.columns c where c.table_schema = 'public' and c.table_name = e.name and c.column_name = e.extra)
      when 'trigger'  then exists (select 1 from pg_trigger t where not t.tgisinternal and t.tgname = e.name)
      when 'policy'   then exists (select 1 from pg_policies p where p.policyname = e.name and p.tablename = e.extra)
      when 'index'    then exists (select 1 from pg_indexes i where i.indexname = e.name)
    end as present
  from expected e
)
select file,
       count(*) filter (where present) as found,
       count(*) as total,
       case when count(*) filter (where present) = count(*) then 'present'
            when count(*) filter (where present) = 0 then 'absent'
            else 'PARTIAL' end as state,
       string_agg(case when not present then kind || ':' || name || case when extra <> '' then '(' || extra || ')' else '' end end, ', ') as missing
from checked
group by file
order by file;
